-- 코드를 입력하세요
SELECT AP.APNT_NO,P.PT_NAME,P.PT_NO,AP.MCDP_CD,D.DR_NAME,AP.APNT_YMD
FROM PATIENT AS P
JOIN APPOINTMENT AS AP ON P.PT_NO=AP.PT_NO
JOIN DOCTOR AS D ON AP.MDDR_ID=D.DR_ID
WHERE AP.APNT_CNCL_YN='N' AND AP.MCDP_CD='CS' AND DATEDIFF(AP.APNT_YMD,'2022/04/13')=0
ORDER BY APNT_YMD
